import { OrgNodeData } from '@/components/OrgChart';

/**
 * PDFから抽出した組織データ
 * 情報・通信部門の組織構造
 * 個人名はmembersプロパティに格納され、組織図には表示されません
 */
export const kuOrgData: OrgNodeData = {
  name: '情報・通信部門',
  title: 'ICT Division',
  description: '部門長：堀内 真人',
  members: [
    { name: '堀内 真人', title: '部門長' },
    { name: '太田 英利', title: '部門長代行' },
    { name: '金児 真利', title: '部門長補佐' },
  ],
  children: [
    {
      name: '企画統轄課',
      title: 'Planning & Administration Section',
      description: '課長：三谷 恭介',
      members: [
        { name: '三谷 恭介', title: '課長' },
        { name: '堀内 勇輝', title: '課長代行' },
        { name: '石岡' },
        { name: '髙原' },
        { name: '磯部' },
        { name: '上信' },
        { name: '窪田' },
        { name: '前平*' },
        { name: '前田(葉)*' },
        { name: '戸谷*' },
        { name: '蜂須賀*' },
      ],
    },
    {
      name: '営業サポートチーム',
      title: 'Business Process Operation Team',
      description: 'チーム長：花嶋 志郎',
      members: [
        { name: '花嶋 志郎', title: 'チーム長' },
        { name: '森川 哲', title: 'チーム長代行' },
        { name: '片柳*' },
        { name: '満田*' },
        { name: '池田(美)*' },
        { name: '小川(優)*' },
      ],
    },
    {
      name: '情報産業ビジネス部',
      title: 'Information Technology Business Department',
      description: '部長：関川 潔',
      members: [
        { name: '関川 潔', title: '部長' },
        { name: '大元 伸一', title: '部長代行' },
        { name: '菅井' },
        { name: '板橋(丸山)' },
        { name: '磯谷' },
      ],
      children: [
        {
          name: 'ITビジネス課',
          title: 'IT Business Section',
          description: '課長：山田 哲生',
          members: [
            { name: '山田 哲生', title: '課長' },
            { name: '工藤 嘉也', title: '課長代行' },
            { name: '伊地知' },
            { name: '杉本' },
            { name: '池田(祐)' },
            { name: '末宗' },
            { name: '原田' },
            { name: '森谷' },
            { name: '小堀' },
            { name: '無敵' },
          ],
        },
        {
          name: 'デジタルバリューチェーン課',
          title: 'Digital Value Chain Section',
          description: '課長：小泉 圭巧',
          members: [
            { name: '小泉 圭巧', title: '課長' },
            { name: '松原 弘貴', title: '課長代行' },
            { name: '木村' },
            { name: '川村' },
            { name: '伊豆田' },
            { name: '齊藤(篤)' },
            { name: '中山(和)' },
            { name: '三澤' },
            { name: '小久保' },
          ],
        },
        {
          name: 'DXコンサルティング課',
          title: 'DX Consulting Section',
          description: '課長：山崎 祐',
          members: [
            { name: '山崎 祐', title: '課長' },
            { name: '渡部 晃史', title: '課長代行' },
            { name: '伊藤（圭）' },
            { name: '丸川' },
            { name: '田中(悠)' },
          ],
        },
      ],
    },
    {
      name: '通信ビジネス部',
      title: 'Communications Business Department',
      description: '部長：(兼)太田 英利',
      members: [
        { name: '(兼)太田 英利', title: '部長' },
        { name: '松本 雄吾', title: '部長代行' },
        { name: '野波' },
      ],
      children: [
        {
          name: 'ＢＰＯビジネス課',
          title: 'BPO Business Section',
          description: '課長：松下 祐生',
          members: [
            { name: '松下 祐生', title: '課長' },
            { name: '薬師寺 健二', title: '課長代行' },
            { name: '田中(啓)' },
            { name: '岡' },
            { name: '髙木(咲)' },
            { name: '藤井' },
            { name: '阿曽*' },
          ],
        },
        {
          name: 'デジタルマーケティングビジネス課',
          title: 'Digital Marketing Business Section',
          description: '課長：清原 延高',
          members: [
            { name: '清原 延高', title: '課長' },
            { name: '竹上 貴之', title: '課長代行' },
            { name: '渡邊(陽)' },
            { name: '荻野' },
            { name: '丸毛' },
            { name: '山崎(賢)' },
            { name: '古田' },
            { name: '澤口' },
          ],
        },
        {
          name: 'モバイルビジネス課',
          title: 'Telecom Business Section',
          description: '課長：山口 恭史',
          members: [
            { name: '山口 恭史', title: '課長' },
            { name: '井上 大輔', title: '課長代行' },
            { name: '曽和' },
            { name: '萩岡' },
            { name: '大村' },
            { name: '朝倉' },
            { name: '小酒井' },
            { name: '藤芳' },
            { name: '杉谷' },
            { name: '菊池(隆)' },
            { name: '米澤' },
          ],
        },
      ],
    },
    {
      name: 'フロンティアビジネス部',
      title: 'Frontier Business Department',
      description: '部長：髙部 公彦',
      members: [
        { name: '髙部 公彦', title: '部長' },
        { name: '佐藤(由)(中松)' },
        { name: '野中' },
        { name: '東馬' },
      ],
      children: [
        {
          name: 'インキュベーション推進課',
          title: 'Incubation Business Section',
          description: '課長：倉島 慶',
          members: [
            { name: '倉島 慶', title: '課長' },
            { name: '笹生 朋樹アイザック', title: '課長代行' },
            { name: '金原' },
            { name: '堀田' },
            { name: '小原(木村)*' },
            { name: '三谷(響)(増田)' },
            { name: '舟越' },
            { name: '古川' },
          ],
        },
        {
          name: '医療・ヘルスケアビジネス課',
          title: 'Medical & Healthcare Business Section',
          description: '課長：児玉 裕幸',
          members: [
            { name: '児玉 裕幸', title: '課長' },
            { name: '清村 篤志', title: '課長代行' },
            { name: '荒井' },
            { name: '傳谷' },
            { name: '黒谷' },
            { name: '中村(優)' },
            { name: '牧尾' },
            { name: '尾曽' },
          ],
        },
        {
          name: '衛星・IPコンテンツビジネス課',
          title: 'Satellite & IP Content Business Section',
          description: '課長：荒巻 裕史',
          members: [
            { name: '荒巻 裕史', title: '課長' },
            { name: '稲留 光', title: '課長代行' },
            { name: '小林(万)' },
            { name: '藤巻' },
            { name: '奥田' },
            { name: '吉澤' },
            { name: '阪田' },
          ],
        },
      ],
    },
  ],
};
